"""GitHub-flavored markdown rendering for PR comments.

The output opens with an HTML marker so the comment can be found and
updated in place on subsequent pushes — one living report per PR instead
of a trail of stale comments.
"""

from __future__ import annotations

from tf_sentry.models import Finding, Report, Severity

COMMENT_MARKER = "<!-- tf-sentry-report -->"

_SEVERITY_ICONS = {
    Severity.CRITICAL: "🟥",
    Severity.HIGH: "🟧",
    Severity.MEDIUM: "🟨",
    Severity.LOW: "🟦",
    Severity.INFO: "⬜",
}


def render_markdown(report: Report, fail_threshold: Severity | None) -> str:
    lines = [COMMENT_MARKER, "## tf-sentry review", ""]

    actions = report.counts_by_action
    if actions:
        stats = " · ".join(f"**{count}** {action}" for action, count in sorted(actions.items()))
        lines.append(f"Plan: {stats}")
    else:
        lines.append("Plan: no resource changes")
    lines.append("")

    if not report.findings:
        lines += ["✅ **No risks detected** by the enabled rules.", ""]
    else:
        gate = (
            f"fails at **{fail_threshold}** and above"
            if fail_threshold is not None
            else "review-only (no fail threshold)"
        )
        verdict = "❌ **failing**" if _fails(report, fail_threshold) else "⚠️ passing"
        lines += [
            f"{verdict} — {len(report.findings)} finding(s); gate {gate}.",
            "",
            "| | Rule | Resource | Finding |",
            "|---|---|---|---|",
        ]
        for finding in report.findings:
            icon = _SEVERITY_ICONS[finding.severity]
            lines.append(
                f"| {icon} {finding.severity} | `{finding.rule_id}` "
                f"| `{_escape(finding.address)}` | {_escape(finding.title)} |"
            )
        lines.append("")

        for finding in report.findings:
            lines += _details_block(finding)

    if report.summary_text:
        lines += [
            "### Blast-radius summary",
            "",
            "> [!NOTE]",
            "> AI-generated, advisory only — it does not affect pass/fail.",
            "",
            report.summary_text,
            "",
        ]

    lines.append(
        '<sub>Generated by <a href="https://github.com/balvanthreddy/tf-sentry">tf-sentry</a>. '
        "Deterministic rules decide pass/fail; see each finding for remediation.</sub>"
    )
    return "\n".join(lines)


def _details_block(finding: Finding) -> list[str]:
    icon = _SEVERITY_ICONS[finding.severity]
    body = [
        "<details>",
        f"<summary>{icon} <code>{finding.rule_id}</code> "
        f"{_escape(finding.title)} — <code>{_escape(finding.address)}</code></summary>",
        "",
        finding.detail,
        "",
    ]
    if finding.evidence:
        body += [f"**Evidence:** `{_escape(finding.evidence)}`", ""]
    if finding.remediation:
        body += [f"**Remediation:** {finding.remediation}", ""]
    body += ["</details>", ""]
    return body


def _fails(report: Report, threshold: Severity | None) -> bool:
    return threshold is not None and report.fails_at(threshold)


def _escape(text: str) -> str:
    return text.replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;")
